//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Headless.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Headless.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No HTML element was found with a matching id, name or text of &apos;{0}&apos;..
        /// </summary>
        internal static string DynamicHtmlPage_DynamicElementNotFound {
            get {
                return ResourceManager.GetString("DynamicHtmlPage_DynamicElementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members that represent HTML elements on the page are read-only. Did you mean to assign a value to the HTML element instance instead of the page? For example: page.InputElement.Value = &quot;test&quot; rather than page.InputElement = &quot;test&quot;...
        /// </summary>
        internal static string DynamicHtmlPage_MembersAreReadOnly {
            get {
                return ResourceManager.GetString("DynamicHtmlPage_MembersAreReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No value has been provided..
        /// </summary>
        internal static string Guard_NoValueProvided {
            get {
                return ResourceManager.GetString("Guard_NoValueProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No form element was found for the requested element..
        /// </summary>
        internal static string HtmlElement_GetHtmlForm_FormNotFound {
            get {
                return ResourceManager.GetString("HtmlElement_GetHtmlForm_FormNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple HTML elements match the criteria but only one element is expected..
        /// </summary>
        internal static string HtmlElement_MultipleMatchesFound {
            get {
                return ResourceManager.GetString("HtmlElement_MultipleMatchesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple elements were found for the attribute &apos;{0}&apos;..
        /// </summary>
        internal static string HtmlElement_MultipleMatchesFoundForAttribute {
            get {
                return ResourceManager.GetString("HtmlElement_MultipleMatchesFoundForAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple elements were found for the id &apos;{0}&apos;..
        /// </summary>
        internal static string HtmlElement_MultipleMatchesFoundForId {
            get {
                return ResourceManager.GetString("HtmlElement_MultipleMatchesFoundForId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple elements were found for the name &apos;{0}&apos;..
        /// </summary>
        internal static string HtmlElement_MultipleMatchesFoundForName {
            get {
                return ResourceManager.GetString("HtmlElement_MultipleMatchesFoundForName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple elements were found for the text &apos;{0}&apos;.
        /// </summary>
        internal static string HtmlElement_MultipleMatchesFoundForText {
            get {
                return ResourceManager.GetString("HtmlElement_MultipleMatchesFoundForText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple elements were found for the value &apos;{0}&apos;..
        /// </summary>
        internal static string HtmlElement_MultipleMatchesFoundForValue {
            get {
                return ResourceManager.GetString("HtmlElement_MultipleMatchesFoundForValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No HTML elements match the criteria..
        /// </summary>
        internal static string HtmlElement_NoMatchFound {
            get {
                return ResourceManager.GetString("HtmlElement_NoMatchFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No option element found with the value or text of &apos;{0}&apos;..
        /// </summary>
        internal static string HtmlList_NoOptionFoundForValue {
            get {
                return ResourceManager.GetString("HtmlList_NoOptionFoundForValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML content was expected but none was provided..
        /// </summary>
        internal static string HtmlPage_NoHtmlContentProvided {
            get {
                return ResourceManager.GetString("HtmlPage_NoHtmlContentProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The url returned was {0} which does not match the expected location of {1}. The responses for this request were:
        ///{2}.
        /// </summary>
        internal static string HttpOutcomeException_InvalidLocation {
            get {
                return ResourceManager.GetString("HttpOutcomeException_InvalidLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status code expected was {0} but {1} was returned. The responses for this request were:
        ///{2}.
        /// </summary>
        internal static string HttpOutcomeException_InvalidResponseStatus {
            get {
                return ResourceManager.GetString("HttpOutcomeException_InvalidResponseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No HttpOutcome have been provided..
        /// </summary>
        internal static string HttpResult_NoHttpOutcomeProvided {
            get {
                return ResourceManager.GetString("HttpResult_NoHttpOutcomeProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple types were found matching {0} that supports the HTML {1}. The following types were matching types:
        ///{2}.
        /// </summary>
        internal static string TypeExtensions_MultipleTypeMatchesForNode {
            get {
                return ResourceManager.GetString("TypeExtensions_MultipleTypeMatchesForNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location is relative where an absolute location is required..
        /// </summary>
        internal static string Uri_LocationMustBeAbsolute {
            get {
                return ResourceManager.GetString("Uri_LocationMustBeAbsolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to edit XML document..
        /// </summary>
        internal static string XPathNavigator_EditNotAllowed {
            get {
                return ResourceManager.GetString("XPathNavigator_EditNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create XML navigator..
        /// </summary>
        internal static string XPathNavigator_NavigatorNotCreated {
            get {
                return ResourceManager.GetString("XPathNavigator_NavigatorNotCreated", resourceCulture);
            }
        }
    }
}
